project:
  type: website
  output-dir: docs

website:
  title: "The CodeSpace"
  search: false
  repo-url: https://github.com/lu-codespace/website
  repo-actions: [edit, issue]
  favicon: github

  page-footer: |
     ![LU-logo](/assets/images/LundUniversity_C2line_BLACK.svg)

  navbar:
    right:
      - about.qmd


format:
  html:
    theme: lux
    css: styles.css
    toc: true
